const swaggerAutogen = require('swagger-autogen')()


const doc = {
    info: {
        version: "1.0.0",
        title: "Ecommerce Prisma Node Typescript API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        apiKeyAuth: {
            type: 'apiKey',
            in: 'header',
            name: 'Authorization',
            description: 'Bearer Token',
        },
    },
    definitions: {
        User: {
            $name: "Jhon Doe",
            $email: "jhondoe@gmail.com",
            password: "#@!!!",
            dob: "2000-05-20"
        },
        Preferences: {
            $preference: "Furniture",
        },
        UserPreferences: {
            $userId: {
                $ref: '#/definitions/User'
            },
            $preferenceId: {
                $ref: '#/definitions/Preferences'
            },
        }
    }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./src/routes/index.ts']

swaggerAutogen(outputFile, endpointsFiles, doc);